vcl 4.1;

import std;

# =========================================================================
# Backends
# =========================================================================

backend imgproxy {
    .host = "imgproxy";        # docker-compose service name
    .port = "8080";
    .first_byte_timeout = 15s;
    .connect_timeout = 2s;
    .probe = {
        .url = "/health";
        .interval = 5s;
        .timeout = 2s;
        .window = 5;
        .threshold = 3;
    }
}

# =========================================================================
# Tenant lookup (see tenants.vcl) — included at build time.
#
#   sub tenant_lookup {
#       if (req.http.X-Tenant-Id == "acme") {
#           set req.http.X-Tenant-Origin  = "https://media.acme-corp.com";
#           set req.http.X-Tenant-MaxDim  = "2048";
#           set req.http.X-Tenant-MaxRPS  = "50";
#       } elsif ...
#       else {
#           set req.http.X-Tenant-Origin = "";  # unknown tenant
#       }
#   }
#
# tenants.vcl is generated by your onboarding tooling whenever a customer
# signs up, then the config is reloaded. Past a few hundred tenants this
# if/elsif chain gets unwieldy — at that point swap tenant_lookup for
# a call into a fast external store (vmod_redis, or an internal HTTP
# lookup service via vmod_curl) instead of regenerating VCL per signup.
# =========================================================================

include "tenants.vcl";

# =========================================================================
# vcl_recv
# =========================================================================

sub vcl_recv {

    if (req.method != "GET" && req.method != "HEAD") {
        return (pass);
    }

    # Route: /t/<tenant_id>/<path-to-image>?w=&h=&fit=&q=
    if (req.url ~ "^/t/[^/]+/") {

        unset req.http.Cookie;
        unset req.http.Authorization;

        set req.http.X-Tenant-Id = regsub(req.url, "^/t/([^/]+)/.*$", "\1");
        set req.http.X-Img-Path  = regsub(req.url, "^/t/[^/]+/([^?]+).*$", "\1");

        call tenant_lookup;

        # Unknown tenant — never falls through to a real fetch.
        if (req.http.X-Tenant-Origin == "") {
            return (synth(404, "Unknown tenant"));
        }

        # --- Parse & validate query params ---------------------------
        # Plain regsub parsing — no extra vmod required. regsub()
        # returns the *unmodified input* when there's no match, so
        # each param is only extracted after confirming it's present.
        if (req.url ~ "(\?|&)w=[0-9]+") {
            set req.http.X-Img-W = regsub(req.url, "^.*(\?|&)w=([0-9]+).*$", "\2");
        } else {
            set req.http.X-Img-W = "0";
        }
        if (req.url ~ "(\?|&)h=[0-9]+") {
            set req.http.X-Img-H = regsub(req.url, "^.*(\?|&)h=([0-9]+).*$", "\2");
        } else {
            set req.http.X-Img-H = "0";
        }
        if (req.url ~ "(\?|&)fit=[a-zA-Z]+") {
            set req.http.X-Img-Fit = regsub(req.url, "^.*(\?|&)fit=([a-zA-Z]+).*$", "\2");
        } else {
            set req.http.X-Img-Fit = "cover";
        }
        if (req.url ~ "(\?|&)q=[0-9]+") {
            set req.http.X-Img-Q = regsub(req.url, "^.*(\?|&)q=([0-9]+).*$", "\2");
        } else {
            set req.http.X-Img-Q = "80";
        }

        # Global hard ceiling regardless of plan, then clamp to the
        # tenant's own plan limit (set in tenants.vcl).
        # Non-numeric/garbage -> "not requested" (0). Numeric but over the
        # global hard ceiling -> clamp to the ceiling, don't zero it out,
        # so the per-tenant clamp below still has a real value to work with.
        if (req.http.X-Img-W !~ "^[0-9]{1,5}$") {
            set req.http.X-Img-W = "0";
        } elsif (std.integer(req.http.X-Img-W, 0) > 4096) {
            set req.http.X-Img-W = "4096";
        }
        if (req.http.X-Img-H !~ "^[0-9]{1,5}$") {
            set req.http.X-Img-H = "0";
        } elsif (std.integer(req.http.X-Img-H, 0) > 4096) {
            set req.http.X-Img-H = "4096";
        }
        if (std.integer(req.http.X-Img-W, 0) > std.integer(req.http.X-Tenant-MaxDim, 2048)) {
            set req.http.X-Img-W = req.http.X-Tenant-MaxDim;
        }
        if (std.integer(req.http.X-Img-H, 0) > std.integer(req.http.X-Tenant-MaxDim, 2048)) {
            set req.http.X-Img-H = req.http.X-Tenant-MaxDim;
        }

        if (req.http.X-Img-Fit !~ "^(cover|contain|fill)$") {
            set req.http.X-Img-Fit = "cover";
        }
        if (req.http.X-Img-Q !~ "^[0-9]{1,3}$" || std.integer(req.http.X-Img-Q, 80) > 100) {
            set req.http.X-Img-Q = "80";
        }

        # Bucket format instead of caching per raw Accept header.
        if (req.http.Accept ~ "image/avif") {
            set req.http.X-Img-Fmt = "avif";
        } elsif (req.http.Accept ~ "image/webp") {
            set req.http.X-Img-Fmt = "webp";
        } else {
            set req.http.X-Img-Fmt = "jpg";
        }

        # Canonical key: tenant-scoped, so two tenants with the same
        # image path never collide, and param order never fragments
        # the cache.
        set req.http.X-Img-Canonical =
            "/t/" + req.http.X-Tenant-Id + "/" + req.http.X-Img-Path +
            "?w="   + req.http.X-Img-W +
            "&h="   + req.http.X-Img-H +
            "&fit=" + req.http.X-Img-Fit +
            "&q="   + req.http.X-Img-Q +
            "&fmt=" + req.http.X-Img-Fmt;

        return (hash);
    }

    return (hash);
}

# =========================================================================
# vcl_hash
# =========================================================================

sub vcl_hash {
    if (req.http.X-Img-Canonical) {
        hash_data(req.http.X-Img-Canonical);
        return (lookup);
    }
    hash_data(req.url);
    if (req.http.host) {
        hash_data(req.http.host);
    } else {
        hash_data(server.ip);
    }
    return (lookup);
}

# =========================================================================
# vcl_backend_fetch — build the real imgproxy advanced URL
# =========================================================================

sub vcl_backend_fetch {
    if (bereq.http.X-Img-Canonical) {
        set bereq.backend = imgproxy;

        if (bereq.http.X-Img-Fit == "cover") {
            set bereq.http.X-Img-RSType = "fill";
        } elsif (bereq.http.X-Img-Fit == "contain") {
            set bereq.http.X-Img-RSType = "fit";
        } else {
            set bereq.http.X-Img-RSType = "force";
        }

        # Source URL is built entirely from the tenant's own registered
        # origin, never from anything the caller supplied directly —
        # this is what makes SSRF a non-issue here: a customer can only
        # ever address paths under their own origin.
        set bereq.http.X-Img-Source = bereq.http.X-Tenant-Origin + "/" + bereq.http.X-Img-Path;

        # /%signature/%processing_options/plain/%source_url
        # imgproxy sits on a private docker network, unreachable from
        # outside this compose stack, so "_" is used in place of a real
        # signature. If that ever changes, sign this with vmod_digest
        # (hmac_sha256 + base64url) using IMGPROXY_KEY/IMGPROXY_SALT.
        set bereq.url = "/_"
            + "/rs:" + bereq.http.X-Img-RSType + ":" + bereq.http.X-Img-W + ":" + bereq.http.X-Img-H
            + "/q:"  + bereq.http.X-Img-Q
            + "/f:"  + bereq.http.X-Img-Fmt
            + "/plain/" + bereq.http.X-Img-Source;

        set bereq.http.Host = "imgproxy";
    }
}

# =========================================================================
# vcl_backend_response
# =========================================================================

sub vcl_backend_response {
    if (bereq.http.X-Img-Canonical) {
        if (beresp.status == 200) {
            set beresp.ttl = 30d;
            set beresp.grace = 6h;
            set beresp.keep = 7d;
        } elsif (beresp.status >= 500) {
            set beresp.ttl = 0s;
            set beresp.uncacheable = true;
            return (deliver);
        } else {
            set beresp.ttl = 1m;
        }
        unset beresp.http.Set-Cookie;
    }
    return (deliver);
}

# =========================================================================
# vcl_deliver
# =========================================================================

sub vcl_deliver {
    if (req.http.X-Img-Canonical) {
        set resp.http.Cache-Control = "public, max-age=2592000, immutable";
        if (obj.hits > 0) {
            set resp.http.X-Cache = "HIT";
            set resp.http.X-Cache-Hits = obj.hits;
        } else {
            set resp.http.X-Cache = "MISS";
        }
    }

    unset resp.http.X-Tenant-Id;
    unset resp.http.X-Tenant-Origin;
    unset resp.http.X-Tenant-MaxDim;
    unset resp.http.X-Tenant-MaxRPS;
    unset resp.http.X-Img-W;
    unset resp.http.X-Img-H;
    unset resp.http.X-Img-Fit;
    unset resp.http.X-Img-Q;
    unset resp.http.X-Img-Fmt;
    unset resp.http.X-Img-RSType;
    unset resp.http.X-Img-Path;
    unset resp.http.X-Img-Source;
    unset resp.http.X-Img-Canonical;

    return (deliver);
}

# =========================================================================
# vcl_backend_error — retry once on total imgproxy failure
# =========================================================================

sub vcl_backend_error {
    if (bereq.http.X-Img-Canonical && bereq.retries < 2) {
        return (retry);
    }
}

# =========================================================================
# vcl_synth — clean 404 for unknown tenants
# =========================================================================

sub vcl_synth {
    if (resp.status == 404 && resp.reason == "Unknown tenant") {
        set resp.http.Content-Type = "text/plain";
        synthetic("unknown tenant");
        return (deliver);
    }
}
